test1

diff --git a/.github/workflows/PR Checks.yml b/.github/workflows/PR Checks.yml
--- a/.github/workflows/PR Checks.yml
+++ b/.github/workflows/PR Checks.yml
@@ -44,7 +44,8 @@ jobs:
         id: convertSource
         if: always()
         run: |
-            echo "$?"            
+            echo "$?"   
+            echo "failure failure() success success()"     
             echo "Coverting source to metadata format"
             echo ${{join(steps.loginToOrg.outputs.*,'\n')}}
             echo ${{steps.loginToOrg.exit_code}}
